public class groovy.lang.ClosureException extends java.lang.RuntimeException
{
    private final groovy.lang.Closure closure;

    public void <init>(groovy.lang.Closure, java.lang.Throwable)
    {
        java.lang.Throwable r6;
        groovy.lang.Closure r3;
        groovy.lang.ClosureException r0;
        java.lang.StringBuffer $r1, $r2, $r4, $r5, $r7;
        java.lang.String $r8;

        r0 := @this: groovy.lang.ClosureException;

        r3 := @parameter0: groovy.lang.Closure;

        r6 := @parameter1: java.lang.Throwable;

        $r1 = new java.lang.StringBuffer;

        specialinvoke $r1.<java.lang.StringBuffer: void <init>()>();

        $r2 = virtualinvoke $r1.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.String)>("Exception thrown by call to closure: ");

        $r4 = virtualinvoke $r2.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.Object)>(r3);

        $r5 = virtualinvoke $r4.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.String)>(" reaason: ");

        $r7 = virtualinvoke $r5.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.Object)>(r6);

        $r8 = virtualinvoke $r7.<java.lang.StringBuffer: java.lang.String toString()>();

        specialinvoke r0.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>($r8, r6);

        r0.<groovy.lang.ClosureException: groovy.lang.Closure closure> = r3;

        return;
    }

    public groovy.lang.Closure getClosure()
    {
        groovy.lang.Closure $r1;
        groovy.lang.ClosureException r0;

        r0 := @this: groovy.lang.ClosureException;

        $r1 = r0.<groovy.lang.ClosureException: groovy.lang.Closure closure>;

        return $r1;
    }
}
