public class org.bouncycastle.util.test.TestFailedException extends java.lang.RuntimeException
{
    private org.bouncycastle.util.test.TestResult _result;

    public void <init>(org.bouncycastle.util.test.TestResult)
    {
        org.bouncycastle.util.test.TestFailedException r0;
        org.bouncycastle.util.test.TestResult r1;

        r0 := @this: org.bouncycastle.util.test.TestFailedException;

        r1 := @parameter0: org.bouncycastle.util.test.TestResult;

        specialinvoke r0.<java.lang.RuntimeException: void <init>()>();

        r0.<org.bouncycastle.util.test.TestFailedException: org.bouncycastle.util.test.TestResult _result> = r1;

        return;
    }

    public org.bouncycastle.util.test.TestResult getResult()
    {
        org.bouncycastle.util.test.TestFailedException r0;
        org.bouncycastle.util.test.TestResult $r1;

        r0 := @this: org.bouncycastle.util.test.TestFailedException;

        $r1 = r0.<org.bouncycastle.util.test.TestFailedException: org.bouncycastle.util.test.TestResult _result>;

        return $r1;
    }
}
